language: generic
sudo: required
dist: trusty
env:
  matrix:
    - EMACS=emacs24
    - EMACS=emacs-snapshot

branches:
  only:
    - master

install:
  - if [ "$EMACS" = 'emacs24' ]; then
      sudo apt-get -qq update &&
      sudo apt-get -qq -f install &&
      sudo apt-get -qq install emacs24 emacs24-el;
    fi
  - if [ "$EMACS" = 'emacs-snapshot' ]; then
      sudo add-apt-repository -y ppa:ubuntu-elisp/ppa &&
      sudo apt-get -qq update &&
      sudo apt-get -qq -f install &&
      sudo apt-get -qq install emacs-snapshot &&
      sudo apt-get -qq install emacs-snapshot-el;
    fi

script:
  - make test

notifications:
  email: false
